# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

WORKDIR /app

# Install dependencies; mcp requires wheels, update pip
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

COPY pyproject.toml .
COPY README.md .
COPY main.py .

# Install pip, and build the package using pip install
RUN pip install --upgrade pip && \
    pip install .

EXPOSE 8080

# Run the MCP server
CMD ["python", "main.py"]
